- themes/solr/templates/htaccess.template
Right now we have to store the artifacts in nightlies.apache.org, but they will have a more permanent location soon.
https://issues.apache.org/jira/browse/INFRA-21504
I have the helm chart repo setup there currently, just for testing but it should work. https://nightlies.apache.org/solr/helm-charts/
I didn't put this under `/solr/operator`, because in the future we will likely have helm charts for Solr Cloud, Solr Prometheus Exporter, and whatever add-ons we have.
> Add rewrite rule to map helm charts

- themes/solr/templates/htaccess.template
This means we can change the location in  https://svn.apache.org/repos/asf/comdev/projects.apache.org/trunk/data/projects.xml  to point to solr website for the DOAP, and once we move source repos, we just change the .htaccess
> SOLR-14497 Use https://solr.apache.org/doap/solr.rdf as DOAP location

- content/pages/community.md
There has been complaints about it being too hard to subscribe/unsubscribe from lists with the new web page's singular link to lists.apache.org location of the list. While that page has buttons for subscribe and unsubscribe, it appears that people get confused, and it also turns out those buttons are not visisble from mobile devices.
This PR adds buttons for each action, see screenshot
It also adds a description about what a mailing list is and how to subscribe.
> Better mailing list description, buttons for (un)subscribe

- themes/solr/templates/htaccess.template
Move nightlies redirects to /solr/release, so that the released artifacts are separate from any nightly artifact/info that may be put in https://nightlies.apache.org/solr.
The CRD releases will be available at: https://solr.apache.org/operator/downloads/crds/{version}/{name}.yaml
> Add CRDs download redirect.

- themes/solr/templates/_javascript.html
- themes/solr/templates/index.html
Received an email to members@ about a new way to include ApacehCon banner on the websites. See https://www.apachecon.com/event-images/
This PR updates this for Solr, see screenshot below. I have made the banner a bit larger and light color instead of black since it is on a white backround.
Before:
After:
> Update ASF event banner to recommended style

- themes/solr/templates/index.html
We highlight several books on the frontpage of Solr site.
However, the newest book is from 2015 - 6 years old, so why would we promote those on the front page? I think it was mentioned in an email thread somewhere too. Here's a PR to remove that section from front page, while keeping them on the resources page.
Instead, we could add sections to the front page about Solr-Operator and/or other relevant things.
> Remove books from frontpage, they are old

- content/solr/security/2021-12-10-cve-2021-44228.md
I also wonder if we should help users recognize that the system property was set correctly.  It's of course visible on the admin screen.
> Log4j: Solr's docker images are mitigated.

- content/solr/security/2021-12-10-cve-2021-44228.md
List conversation: https://lists.apache.org/thread/x1qkgyqxtb6mko1qr2qhq40j96q07sy7
Also made references to Log4J consistent in capitalization.
> Log4J: Prometheus Exporter isn't vulnerable

- content/solr/security/2021-12-10-cve-2021-44228.md
See https://issues.apache.org/jira/browse/SOLR-15850
Not all docker versions / tags are updated with the sysprop, so we should specify that the tags listed as "supported" on hub are the ones that are safe. By policy that is all 8.x verions, latest 7.7 version, latest 6.x version, latest 5.x version.
> Clarify what docker versions are patched

- content/solr/security/2021-12-10-cve-2021-44228.md
This adds a note about the followup CVE-2021-45046 and makes clear that SOlr is not affected.
> Add a note about CVE-2021-45046

- content/solr/security/2021-12-10-cve-2021-44228.md
and refer to the Wiki for some more explanations.
> Log4shell: Justify log4j2.formatMsgNoLookups

- content/solr/security/2021-12-10-cve-2021-44228.md
and refer to the Wiki for some more explanations.
> Log4shell: Justify log4j2.formatMsgNoLookups (#62)

- themes/solr/templates/htaccess.template
Nightlies has been shown to not be stable today, so we need to move the CRD redirect to the archives. (Older non-apache releases are not in the archives, so we will continue to redirect those to the nightlies server)
We also need to move the helm charts, but that can be done separately.
> Redirect Apache CRDs to the archives instead of nightlies

- plugins/vex/vex.py
> Fix passing a custom output path to the vex plugin

- vex-input.json
The only places we use json-path is for querying (via Calcite) and for transforming/indexing custom JSON. Since the advisory describes a problem that is limited to the current thread, and users that are allowed to query/transform/index are already trusted to cause load to some extent, this advisory does not appear to have impact on the way json-path is used in Solr.
> Suppress CVE-2023-51074

- content/pages/blogposts/2024-06-17-hybrid-search.md
Added the blogpost about Hybrid Search
> Blogpost about Hybrid Search

- README.md
- build.sh
- manual-install.md
In #104 I moved the `build.sh` script from requiring a local python and pelican install, to using a docker image locally.
The script has some weaknesses and bugs.
* The chained commands `pip` and `pelican` were not passed correctly to docker runtime, causing error 
`./build.sh: line 64: pelican: command not found`
* The requirements needed to be pulled every single time
This PR addresses this
* On first run, check if a local image `solr-pelican-image` is present. If not, build the image. If it exists, use it as-is
* Re-build image if `requirements.txt` is newer than latest image build time
* Add proper getopts argument parsing with pass-through of options to pelican (e.g. `-v` for verbose)
* Uses `python:3-alpine` as image, smaller and no need for preinstalled pelican v4.8.0
This all …
> Improve build script

- themes/solr/templates/bloghome.html
I noticed when testing the latest PR #114 locally that the post, dated July 15th, sorted above the existing July 1st post. It is since the template explicitly sorts by the english surface form of the date. Here is a small patch that sorts by reverse of the plain file listing, which already contains the date...
> Sort blog posts reverse date

- content/solr/solr_news/2024-10-25-solr8-eol.md
- themes/solr/templates/downloads.html
Made a small news page, and changed the downloads to state 8.11 is EOL
> EOL Solr 8

- content/solr/security/2025-01-26-cve-2024-52012.md
- content/solr/security/2025-01-26-cve-2025-24814.md
- CVE-2024-52012
- CVE-2025-24814
> Add security notices for two recent CVEs

- .asf.yaml
The operator release process involves some pushes directly to the `main` and `production` branches of this repo.  Both attempts to push triggered a minor error due to a syntax error in this repo's `.asf.yaml`:
```
Total 15 (delta 8), reused 0 (delta 0), pack-reused 0
remote: To github:apache/solr-site.git
remote:    ea9723c82..bc90fbd27  bc90fbd27d5c58deeb550120b09be3ee28827f64 -> main
remote: Syncing refs/heads/main...
remote: Sending notification emails to: ['"commits@solr.apache.org" <commits@solr.apache.org>']
remote: An error occurred while processing the github feature in .asf.yaml: 
remote: 
remote: when expecting a mapping
remote: found arbitrary text
remote:   in "solr-site.git/.asf.yaml::github", line 10, column 1:
remote:     protected_branches: main production
remote:     ^ …
```
> Resolve asf.yaml syntax error

- vex-input.json
This change adds a VEX statement for CVE-2024-51504, concluding that the vulnerability is **not exploitable in typical production deployments** of Apache Solr (versions 3.4.0 to 3.8.1). The assessment is based on the following configuration-dependent conditions:
- Solr must be running in [SolrCloud mode](https://solr.apache.org/guide/solr/latest/deployment-guide/cluster-types.html#solrcloud-mode), which uses Zookeeper.
- The [embedded Zookeeper server](https://solr.apache.org/guide/solr/latest/deployment-guide/zookeeper-ensemble.html) must be in use — a configuration **explicitly** discouraged for production environments. Solr logs a warning when this setup is active, supporting the conclusion that it is not commonly used in production.
- The Zookeeper Admin Server must be manually …
> SOLR-17809: Add VEX for CVE-2024-51504 (Zookeeper)
