- themes/solr/templates/htaccess.template
Once we switch GIT repo location, we need to merge this, to change location of solr DOAP file
> Update location of our DOAP file when switching to solr.git repo

- content/doap/solr-operator.rdf
https://issues.apache.org/jira/browse/SOLR-15211
> Adding a RDF file for the solr operator

- themes/solr/templates/index.html
Noticed the wording when looking at the site in connection with the (unrelated) #13 changes.
> change "continue your mastery" to "continue to learn"

- themes/solr/templates/operator/downloads.html
- themes/solr/templates/operator/index.html
Will leave this open while people try out the staging site.
> Fixes for the new Operator Site.

- content/pages/resources.md
- themes/solr/static/css/base.css
- themes/solr/static/css/operator.css
- themes/solr/templates/downloads.html
- themes/solr/templates/index.html
https://issues.apache.org/jira/browse/SOLR-15240
Adds entries to main index page, as well as links to their tutorials.
The CSS changes make the grids look better.
> SOLR-15239: Add kube & docker info to main site.

- themes/solr/static/css/base.css
- themes/solr/static/css/operator.css
- themes/solr/static/javascript/main.js
- themes/solr/templates/base.html
- themes/solr/templates/index.html
- themes/solr/templates/operator/index.html
There would be a news entry for Solr and the Solr Operator if there are two releases within the last 2 months.
> Show Solr Operator news update on main page

- themes/solr/templates/downloads.html
- themes/solr/templates/operator/artifacts.html
https://issues.apache.org/jira/browse/SOLR-15773
> SOLR-15773 Download directly, without landing on the mirrors page

- content/solr/security/2021-12-10-cve-2021-44228.md
Docker images mitigated.
Prometheus not impacted
> Update production site

- content/solr/security/2021-12-10-cve-2021-44228.md
> Add note about CVE-2021-45105

- themes/solr/templates/downloads.html
Proposed disclaimer to help users understand the risk of downloading v7.7.3.
> Disclaimer for 7.7.3 release

- content/pages/community.md
> SOLR-15432: update link to current irc home

- themes/solr/templates/htaccess.template
Part of https://github.com/apache/solr-operator/issues/421
> Merge CRD to official repo redirect into production

- content/pages/community.md
- content/pages/operator/community.md
reference: https://infra.apache.org/git-primer.html#repocheckout
> community.md - fix git clone gitbox links

- content/pages/security.md
Hopefully less people will email the list with these issues.
> Warn about scans in security section.

- content/pages/security.md
Co-authored-by: David Smiley <dsmiley@apache.org>
> Warn about scans in security section. (#80)

- content/.well-known/security.txt
https://issues.apache.org/jira/browse/SOLR-16518
> SOLR-16518 Add security.txt to website

- content/pages/security.md
- pelicanconf.py
- plugins/vex/__init__.py
- plugins/vex/schema/bom-1.4.schema.json
- plugins/vex/schema/vex-input.schema.json
- plugins/vex/vex.py
- requirements.txt
- themes/solr/templates/security.html
- vex-input.json
To replace https://cwiki.apache.org/confluence/display/SOLR/SolrSecurity#SolrSecurity-SolrandVulnerabilityScanningTools and ask for collaboration and experiences on approaches to VEX as discussed in https://lists.apache.org/thread/j35clzm48s7xxc9671qogzr54bsdj1lz
> Share dependency vulnerability info

- vex-input.json
> remove 'known' derby problem with CVE

- themes/solr/templates/htaccess.template
See https://lists.apache.org/thread/99zp5cnhpwlfc022fcrwkhgmtvjygdvx
> Fix DOAP redirect to github instead of gitbox

- .asf.yaml
> Remove pelican from asf.yaml on production branch

- .asf.yaml
- .github/workflows/build-pelican.yml
Ref email to PMC and instructions at https://cwiki.apache.org/confluence/display/INFRA/Moving+from+Infrastructure-pelican+to+GitHub+Actions
> Build site with github action

- .asf.yaml
- .github/workflows/build-pelican.yml
- .github/workflows/pr-build-pelican.yml
- pelicanconf.py
- requirements.txt
This will help github action to run without our custom py modules required by vex
> WIP: Temporarily disable vex pluging

- .github/workflows/build-pelican.yml
- pelicanconf.py
- requirements.txt
Discovered some package incompatibilities preventing me from running locally. This should fix it.
> Bump package versions

- themes/solr/templates/security.html
Until https://github.com/apache/infrastructure-actions/pull/63 is resolved
> Add a static copy of the VEX table

- content/pages/blogposts/2024-07-01-birds-of-a-feather.md
Added the blogpost about Birds of a Feather
> Blogpost about Community Over Code EU - Birds of a Feather

- content/pages/blogposts/2024-07-27-apache-solr-neural-search-tutorial.md
I added a new blog post about Apache Solr Neural Search Tutorial
> Blog post Apache Solr Neural Search Tutorial

- content/pages/blogposts/2024-07-27-apache-solr-neural-search-tutorial.md
Apache Solr neural search tutorial post
> Create 2024-07-27-apache-solr-neural-search-tutorial.md (#117)

- themes/solr/templates/downloads.html
https://issues.apache.org/jira/browse/SOLR-17295
> SOLR-17295 Add download link for OpenAPI

- themes/solr/templates/fullwidth.html
Solr uses variations of the blurb below to describe itself on solr.apache.org
> Solr is the popular, blazing-fast, open source enterprise search platform built on Apache Lucene [...]
This has served us well for years, but a few reasons call for a refresh:
1. Copies of this description have varied apart over time and need realigned
2. The description misses (or underplays) some of Solr's newer features (e.g. vector search)
3. Longer forms of the description emphasize features that aren't meaningful differentiators (e.g. XML-based APIs, scalability) in today's tech landscape.
This PR (along with accompanying changes to the operator and main repo) updates and unifies the language the project uses to describe itself.
> Modernize project description

- content/pages/blogposts/2024-09-16-community-over-code-north-america-2024.md
A new blog post about the Community Over Code NA 2024. Let me know if publishing blog news about ASF (and Apache Solr) events and conferences is ok.
> Blog post - Community Over Code NA 2024

- content/pages/blogposts/2024-09-16-community-over-code-north-america-2024.md
* community over code NA new blogpost - conference
> Blog post - Community Over Code NA 2024 (#126)

- content/pages/blogposts/2024-10-09-categorical-features-in-apache-solr-learning-to-rank.md
added a blog post about Categorical Features in Apache Solr Learning to Rank
> Categorical Features - Blog Post

- themes/solr/templates/_matomo.html
- themes/solr/templates/base.html
- themes/solr/templates/operator/base.html
https://issues.apache.org/jira/browse/SOLR-17633
> SOLR-17633 Enable Matomo tracking

- content/pages/blogposts/2025-06-03-solr-autogeneratephrasequeries-and-minimum-should-match-with-synonyms.md
> Blog Post Solr AutoGeneratePhraseQueries and MM with synonyms

- themes/solr/templates/downloads.html
Re-enable for 9.x once 10.0 is released
> Disable 8.x download section as it is EOL
